@startuml

actor Pracownik

usecase (Definiowanie samochodu)
usecase (Definiowanie usterek)
usecase (Wybór części)
usecase (Zamówienie części)
usecase (Odebranie części)
usecase (Zlecenie napraw)
usecase (Potwierdzenie napraw)
usecase (Drukowanie faktury)
usecase (Płatność)

Pracownik -- (Definiowanie samochodu)
Pracownik -- (Definiowanie usterek)
Pracownik -- (Wybór części)
Pracownik -- (Zamówienie części)
Pracownik -- (Odebranie części)
Pracownik -- (Zlecenie napraw)
Pracownik -- (Potwierdzenie napraw)
Pracownik -- (Drukowanie faktury)
Pracownik -- (Płatność)

@enduml